
# Site settings
title: YUNFENG-NET.GTIHUB.IO BLOG
theme: jekyll-theme-merlot

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
